spring.application.name=DebtMates-BE

server.reactive.session.cookie.same-site=strict

# application.properties
server.port=8080
spring.datasource.url=jdbc:postgresql://DebtMates_postgres_container:5432/debtMateDB
spring.datasource.username=test
spring.datasource.password=1234

spring.data.redis.host=DebtMates_redis_container
spring.data.redis.password=test
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


# Gemini API properties
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent

# Email configuration ( example for Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OTP expiration (5 minutes in milliseconds)
otp.expiration=300000

#Cloudinary configuration
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

